name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: JustEnoughMod/DoxygenDeployAction@1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh_pages
          folder: .
          config_file: doxyfile
